version: "3.1"
services:

  mysql_db:
    build: ./db
    restart: "no"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    hostname: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: advertising_service

  web-app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    hostname: web-app
    depends_on:
      - mysql_db
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=root
      - DATABASE_NAME=advertising_service
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=secret